name: Maven Package

on:
  release:
    types: [created]
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Release
        uses: mg-smartrent/github-actions-maven-release@v1.5
        with:
          git-release-bot-name: "release-bot"
          git-release-bot-email: "release-bot@example.com"
          access-token: ${{ secrets.MAVEN_PUBLISH_TOKEN }}"

